server:
  port: 9099

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver


    username: sa
    password:
#
#    url: jdbc:mysql://localhost:3306/opsan1_demo?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  application:
    name: profile

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: muilat.champ@gmail.com
    password: password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
#    initialize-schema: always

# Auth server setting
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
      id: profile
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:9191/oauth/authorize
      access-token-uri: http://localhost:9191/oauth/token

input: file:C:/Users/PolarisDigitech/Documents/workspace/demo/src/main/resources/data.csv

#logging
logging:
  file: my-application.log
#  level: info
